<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE imobiliaria [
<!ELEMENT imobiliaria (imovel+)>
<!ELEMENT imovel (descricao,proprietario,endereco,caracteristicas,valor)>
<!ELEMENT descricao (#PCDATA)>
<!ELEMENT valor (#PCDATA)>

<!ELEMENT proprietario (nome, (email|telefone)+)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT telefone (#PCDATA)>

<!ELEMENT endereco (rua,bairro,cidade,número?)>
<!ELEMENT rua (#PCDATA)>
<!ELEMENT bairro (#PCDATA)>
<!ELEMENT cidade (#PCDATA)>
<!ELEMENT número (#PCDATA)>

<!ELEMENT caracteristicas (tamanho,numQuartos,numBanheiros)>
<!ELEMENT tamanho (#PCDATA)>
<!ELEMENT numQuartos (#PCDATA)>
<!ELEMENT numBanheiros (#PCDATA)>
]>

<imobiliaria>
    <imovel>
        <descricao>Casa próxima à praia.</descricao>
        <proprietario>
            <nome>Carlos Luís</nome>
            <email>luisc@email.com</email>
            <telefone>91234-5678</telefone>
        </proprietario>
        <endereco>
            <rua>rua rua</rua>
            <bairro></bairro>
            <cidade>Natal</cidade>
        </endereco>
        <caracteristicas>
            <tamanho>80m²</tamanho>
            <numQuartos>2</numQuartos>
            <numBanheiros>1</numBanheiros>
        </caracteristicas>
        <valor>50000</valor>
    </imovel>

    <imovel>
        <descricao>Apartamento de luxo com varanda grande.</descricao>
        <proprietario>
            <nome>Isabelly Lima</nome>
            <email>Isa@email.com</email>
            <telefone>99012-3456</telefone>
            <telefone>97890-1234</telefone>
        </proprietario>
        <endereco>
            <rua>rua rua</rua>
            <bairro></bairro>
            <cidade>João Pessoa</cidade>
            <número>44</número>
        </endereco>
        <caracteristicas>
            <tamanho>70m²</tamanho>
            <numQuartos>2</numQuartos>
            <numBanheiros>2</numBanheiros>
        </caracteristicas>
        <valor>65000</valor>
    </imovel>

    <imovel>
        <descricao>Casa com quintal e garagem para 2 carros.</descricao>
        <proprietario>
            <nome>Gercina dos Santos</nome>
            <telefone>95678-9012</telefone>
        </proprietario>
        <endereco>
            <rua>rua rua</rua>
            <bairro></bairro>
            <cidade>Caicó</cidade>
            <número>80</número>
        </endereco>
        <caracteristicas>
            <tamanho>200m²</tamanho>
            <numQuartos>3</numQuartos>
            <numBanheiros>2</numBanheiros>
        </caracteristicas>
        <valor>200000</valor>
    </imovel>
</imobiliaria>